AllCops:
  TargetRubyVersion: "2.5"

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - db

Naming/FileName:
  Exclude:
    - 'lib/d-tune.rb'

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false
